#-----------------------------------
# Game Structs
#   This file holds most of the data structs.
#   Each module will need to add a struct with their metadata.
#
# MIT License
#-----------------------------------

%lang starknet

# struct holding how much resources does it cost to build/buy a thing
struct Cost:
    # the count of unique ResourceIds necessary
    member resource_count : felt
    # how many bits are the packed members packed into
    member bits : felt
    # packed IDs of the necessary resources
    member packed_ids : felt
    # packed amounts of each resource
    member packed_amounts : felt
end

struct CryptData:
    member resource : felt  # uint256 - resource generated by this dungeon (23-28)
    member environment : felt  # uint256 - environment of the dungeon (1-6)
    member legendary : felt  # uint256 - flag if dungeon is legendary (0/1)
    member size : felt  # uint256 - size (e.g. 6x6) of dungeon. (6-25)
    member num_doors : felt  # uint256 - number of doors (0-12)
    member num_points : felt  # uint256 - number of points (0-12)
    member affinity : felt  # uint256 - affinity of the dungeon (0, 1-58)
    # member name : felt  # string - name of the dungeon
end

struct PackedSquad:
    # one packed troop fits into 2 bytes (troop ID + vitality)
    # one felt is ~31 bytes -> can hold 15 troops
    # a squad has 25 troops -> fits into 2 felts when packed
    member p1 : felt  # packed Troops t1_1 ... t1_15
    member p2 : felt  # packed Troops t1_16 ... t3_1
end

struct RealmBuildings:
    member fairgrounds : felt
    member royal_reserve : felt
    member grand_market : felt
    member castle : felt
    member guild : felt
    member officer_academy : felt
    member granary : felt
    member housing : felt
    member amphitheater : felt
    member archer_tower : felt
    member school : felt
    member mage_tower : felt
    member trade_office : felt
    member architect : felt
    member parade_grounds : felt
    member barracks : felt
    member dock : felt
    member fishmonger : felt
    member farms : felt
    member hamlet : felt
end

# this struct holds everything related to a Realm & combat
# a Realm can have two squads, one used for attacking
# and another used for defending; this struct holds them
struct RealmCombatData:
    member attacking_squad : PackedSquad
    member defending_squad : PackedSquad
    member last_attacked_at : felt
end

struct RealmData:
    member regions : felt # here we have regionS, and at TraitIds we have Region
    member cities : felt
    member harbours : felt
    member rivers : felt
    member resource_number : felt
    member resource_1 : felt
    member resource_2 : felt
    member resource_3 : felt
    member resource_4 : felt
    member resource_5 : felt
    member resource_6 : felt
    member resource_7 : felt
    member wonder : felt
    member order : felt
end

struct ResourceOutput:
    member resource_1 : felt
    member resource_2 : felt
    member resource_3 : felt
    member resource_4 : felt
    member resource_5 : felt
    member resource_6 : felt
    member resource_7 : felt
end

struct Troop:
    member id : felt  # TroopId
    member type : felt  # TroopType
    member tier : felt
    member agility : felt
    member attack : felt
    member defense : felt
    member vitality : felt
    member wisdom : felt
end

# # TODO: add a t4 Troop that's a Character from our Character module;
# #       it should be optional
struct Squad:
    # tier 1 troops
    member t1_1 : Troop
    member t1_2 : Troop
    member t1_3 : Troop
    member t1_4 : Troop
    member t1_5 : Troop
    member t1_6 : Troop
    member t1_7 : Troop
    member t1_8 : Troop
    member t1_9 : Troop
    member t1_10 : Troop
    member t1_11 : Troop
    member t1_12 : Troop
    member t1_13 : Troop
    member t1_14 : Troop
    member t1_15 : Troop
    member t1_16 : Troop

    # tier 2 troops
    member t2_1 : Troop
    member t2_2 : Troop
    member t2_3 : Troop
    member t2_4 : Troop
    member t2_5 : Troop
    member t2_6 : Troop
    member t2_7 : Troop
    member t2_8 : Troop

    # tier 3 troop
    member t3_1 : Troop
end

struct SquadStats:
    member agility : felt
    member attack : felt
    member defense : felt
    member vitality : felt
    member wisdom : felt
end
